# Generated by Django 5.2.10 on 2026-02-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
